# services:
#   frontend:
#     image: upward-frontend:dev
#     working_dir: /app
#     command: npm run dev -- --host 0.0.0.0 --port 5173
#     ports:
#       - "5173:5173"
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     # volumes:
#     #   - ./:/app # was ./Frontend:/app -> caused Frontend/Frontend
#     #   - /app/node_modules
services:
  frontend:
    image: upward-frontend:dev
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
